import React, { useEffect } from 'react'
import Head from "next/head";
import { useState } from "react";
import { search_product } from '../../redux/redux_call';

const axios = require('axios');
export default function Navbar() {
  const [products, setproduct] = useState([]);
  const [category, setcategory] = useState();

  const inputhandle = (e) => {
    setcategory(e.target.value);
  }
  const clickbtn = (e) => {
    e.preventDefault();
    search_product(category).then(data => {
      setproduct([data]);
    });
  }

  return (

    <>
      <Head>
        <title>Navbar Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://tea.fit/cdn/shop/files/Flipkart-white.png?v=1694755122&width=550" />
      </Head>
      <div className='col-md-12'>
        <nav className="navbar navbar-expand-lg bg-body-tertiary">
          <div className="container">
            <a className="navbar-brand" href="#">Amazon</a>
            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarSupportedContent">
              <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                <li className="nav-item">
                  <a className="nav-link " aria-current="page" href="#">Home</a>
                </li>
                <li className="nav-item">
                  <a className="nav-link " aria-current="page" href="#">Service</a>
                </li>
                <li className="nav-item">
                  <a className="nav-link " aria-current="page" href="#">Contact</a>
                </li>
                <li className="nav-item">
                  <a className="nav-link " aria-current="page" href="#">About</a>
                </li>
                <li className="nav-item">
                  <a className="nav-link " aria-current="page" href="#">Blog</a>
                </li>

              </ul>
              <form className="d-flex" role="search">
                <input className="form-control me-2" type="search" value={category} onChange={(e) => { inputhandle(e) }} placeholder="Search" aria-label="Search" />
                <button className='btn btn-outline-primary' onClick={clickbtn}>search</button>
              </form>
            </div>
          </div>
        </nav>
      </div>
      <div className="col-md-12">
        <div className="container">
          <div className="col-md-12">

            {products != null && (
              <>
                {console.log('products  ', products)}
                {
                  products.map((item, index) => {
                    return (
                      <div key={index}>
                        <div class="product-card">
                          <div class="badge">Hot</div>
                          <div class="product-tumb">
                            <img src="https://i.imgur.com/xdbHo4E.png" alt="" />
                          </div>
                          <div class="product-details">
                            <span class="product-catagory">{item.title}</span>
                            <h4><a href="">{item.category}</a></h4>
                            <p>{item.description}</p>
                            <div class="product-bottom-details">
                              <div class="product-price"><small>$96.00</small>$230.99</div>
                              <div class="product-links">
                                <a href=""><i class="fa fa-heart"></i></a>
                                <a href=""><i class="fa fa-shopping-cart"></i></a>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    )
                  })
                }
              </>
            )}




          </div>
        </div >
      </div >






    </>
  )
}
